name: Daily Update
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Site
        run: python autopilot.py
      - name: Save Changes
        run: |
          git config --global user.name 'Nexus-CEO'
          git config --global user.email 'ceo@nexus.ai'
          git add .
          git commit -m "Auto-update"
          git push
